### ISSUE TITLE
[Bug]: Fingerprint Unlock Condition

### ISSUE THREAD

**Issue by Penguinlay** [ParetoSecurity/pareto-mac#108]
### What happened?

Fingerprint unlocks fail two security check with correct config:
- https://paretosecurity.com/security-checks/password-preferences
- https://paretosecurity.com/security-checks/password-inactivity
- https://paretosecurity.com/security-checks/screensaver

### Version

HW: MacBook Pro (16-inch, 2021)
macOS: 12.3 Beta (21E5196i)
App Version: 1.6.40
Build: 4224

**Comment by Penguinlay** [comment]
Note that this happens after the unlock from 5mins screensaver activation. Running the check again manually after the unlock will pass all those tests.

**Comment by Penguinlay** [comment]
> Are you a Setapp user?
> 
> We have a release in the review that should go out in a couple of days.

Yup, looking forward to it then!

**Comment by dz0ny** [comment]
This should now be resolved, please check if you still have an issue.

**Comment by Penguinlay** [comment]
It is fixed! I will close this for now. Thank you!
