### ISSUE TITLE
[Bug]: Remote Login theoretical case

### ISSUE THREAD

**Issue by drewhamlin** [ParetoSecurity/pareto-mac#111]
### What happened?

You might disagree with this but technically if Remote Login is enabled but access is set to "Only these users" and the users list is empty, then Remote Login is actually turned off.

(My employer forces the "Remote Login" checkbox on, but they don't reset any contents of the users list, so I'm stuck with the global checkbox on but am technically in adherence of the security rule since no users are allowed access.)

### Version

1.6.51 - 4331

**Comment by zupo** [comment]
Hey Drew!

I do agree that you are probably fine with remote access enabled but empty list of allowed users. I suggest you disable the Remote Access check for your machine. 

Nevertheless, I would be uncomfortable marking such a machine safe for everyone, though. Even if no users are allowed, the device is still open for connection and there might be a security flaw in the wild that works around the users list. Hence, to really be safe, the SSH port needs to be closed.
