### ISSUE TITLE
[Bug]: AirDrop security checks page has mistakes

### ISSUE THREAD

**Issue by drewhamlin** [ParetoSecurity/pareto-mac#119]
### What happened?

There are a few mistakes on this page:
https://paretosecurity.com/security-checks/airdrop

1. The word "Contacts" is misspelled as "Contacs" (and, at least in the US, the word "only" is capitalized in the Finder dropdown menu as well)
2. The image appears broken and there is some stray content at the bottom of the page that says "diff --git a/src/minisites/sites/paretosecurity_com/static/images/security-checks/airdrop.png b/src/minisites/sites/paretosecurity_com/static/images/security-checks/airdrop.png"
3. The option referred to as "Off" appears in the Finder as "No One" (at least in the US)

### Version

1.6.72 - 4663

**Comment by dmurko** [comment]
This looks like someone did not review the page before publishing. :) We'll have it fixed soon, thanks for reporting!

**Comment by dz0ny** [comment]
And fixed :)
