### ISSUE TITLE
[Bug]: AirDrop misinterpreting default value?

### ISSUE THREAD

**Issue by drewhamlin** [ParetoSecurity/pareto-mac#120]
### What happened?

I noticed the latest version of the app, which includes the AirDrop security check, was failing for me on a couple of Macs. It was saying I needed to set the setting to Contacts Only, but the setting actually was set to this.

In each case, setting it to Everyone and then back to Contacts Only resolved the issue.

I’m wondering though, if these Macs were in their default value for this feature and it has never been modified before. I could see how Pareto might not be handling a situation where AirDrop was in its default Contacts Only state, only handling instead if it was modified into this state. I’m not 100% that this is the issue, but I suspect it may be.

### Version

Latest

**Comment by dz0ny** [comment]
You are correct, a new version was released that takes into account the defaults. Thanks for reporting.
