### ISSUE TITLE
[Feature Request]: Support outdated Homebrew packages

### ISSUE THREAD

**Issue by nicekiwi** [ParetoSecurity/pareto-mac#128]
### What happened?

This might be a bit hard, but checking for security updates for Homebrew packages could be a cool feature to monitor dev tooling status. I assume a register of homebrew package security status exists somewhere. 🤞

### Version

Version: HW: MacBook Air (M1, 2020)
macOS: 12.5.0
App Version: 1.7.12
Build: 4861
Location: /Applications/Pareto Security.app
Build: app-live-team

**Comment by zupo** [comment]
The main downside I see is that to do this, Pareto app would need to request the "Full Disk Access" permission from the user. But we already do this for the optional check to verify Time Machine backups are encrypted. So, should be possible?

Let's see if we can get a couple of 👍 's from other people!

**Comment by dz0ny** [comment]
Docs published on https://paretosecurity.com/blog/run-custom-checks-in-auditor
