### ISSUE TITLE
[Bug]: Firewall Stealth Mode is reported as disabled, even though it is enabled

### ISSUE THREAD

**Issue by kirby** [ParetoSecurity/pareto-mac#135]
### What happened?

Firewall Stealth Mode is reported as disabled, even though it is enabled

https://paretosecurity.com/auditor/checks/firewall

macOS 13.2.1 (22D68)

- Enabled Firewall Stealth Mode
- Run Checks
 

### Version

Pareto Security 1.7.6.0 - 5221

**Comment by dz0ny** [comment]
Hi, this is usually not a bug but a broken firewall config. 

Verify with and report back:

```/usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate --getblockall --getallowsigned --getstealthmode```
