### ISSUE TITLE
[Bug]: Firewall stealth mode check returns false positive

### ISSUE THREAD

**Issue by costingalan** [ParetoSecurity/pareto-mac#137]
### What happened?

Hello,

The firewall stealth mode check returns a false positive for me: 
<img width="477" alt="Screenshot 2023-04-30 at 13 41 44" src="https://user-images.githubusercontent.com/13436165/235348866-f977a828-9cf5-4e3c-a924-54c6b12f8a5e.png">
<img width="481" alt="Screenshot 2023-04-30 at 13 44 54" src="https://user-images.githubusercontent.com/13436165/235348871-c9ec1b74-b5f9-4c00-83e2-51197d1cccba.png">

Is there a way to check besides the Mac UI if the stealth option is actually enabled? Or something else that I can do?

Thank you and have a great day ahead,
Costin Galan

### Version

HW: MacBook Pro (MacBookPro16,1) macOS: 13.3.1 App: Pareto Auditor App Version: 1.7.64 Build: 5236, SetApp license

**Comment by zupo** [comment]
Hey, try this: https://github.com/ParetoSecurity/pareto-mac/issues/135

**Comment by costingalan** [comment]
Hey @zupo ! Thanks for the hint. Somehow I missed that issue when searching. I've enforced it via CLI and it passed the checks.
