### ISSUE TITLE
[Bug]:  Preferences for "Checks" Unavailable After a Clean Install

### ISSUE THREAD

**Issue by zonemaster42** [ParetoSecurity/pareto-mac#140]
### What happened?

I needed to perform a clean install of Pareto Security on my **2019 iMac**, after deleting & reinstalling my user account to fix some unrelated errors.

The "**Checks**" preference page no longer displays any options. Clicking in the blank space where the options would be listed, crashes Pareto Security.

To further evaluate the problem, I performed the following steps on my **MacBook Pro**:
1. Verified that the "**Checks**" page was working on the latest version.
2. Completely removed Pareto Security via CleanMyMac X.
3. Rebooted.
4. Reinstalled Pareto Security via Setapp.
5. Verified that the "**Checks**" options page was blank (**ERROR**)!

Note that steps 2-5 have been performed on both my iMac & MacBook several times.

_THE ERROR PERSISTS ON BOTH MACHINES!_

I have relied on Pareto Security in the past. I hope to see a resolution soon.

![CleanShot 2024-04-17 at 20 58 15@2x](https://github.com/ParetoSecurity/pareto-mac/assets/12567001/8fc8f4ef-fa1d-45f7-a99e-744d41c90f87)

### Version

HW: MacBook Pro (MacBookPro16,1) macOS: 14.4.1 
App: Pareto Auditor App Version: 1.7.81 Build: 5441

### Relevant log output

```shell
Location: /Applications/Setapp/Pareto Security.app
Build: app-live-setapp
IsAdmin: true

Logs:

Location: /Users/stan/Library/Logs/niteo.co.Pareto-setapp/Setapp-1.log
Logs:


[17-04-2024 20:01:10.45] [Debug] > Migrating from `1.6.6` to `2.0.1`
[17-04-2024 20:01:10.45] [Debug] > Finished migration process from `1.6.6` to `2.0.1`
[17-04-2024 20:01:10.53] [Info] > Framework version: 3.5.0 (11).
[17-04-2024 20:01:10.53] [Debug] [Configuration] > did set configuration: SetappConfiguration(publicKeyFilename: setappPublicKey.pem, publicKeyBundle: NSBundle </Applications/Setapp/Pareto Security.app> (loaded))
[17-04-2024 20:01:10.53] [Info] [Configuration] > configuration was updated
[17-04-2024 20:01:10.53] [Info] [Configuration] > no changes in configuration
[17-04-2024 20:01:10.53] [Warning] [Configuration] > configuration isn't validated
[17-04-2024 20:01:10.53] [Info] [Configuration] > validate configuration
[17-04-2024 20:01:10.53] [Info] [Configuration] > public key located
[17-04-2024 20:01:10.54] [Debug] [XPCConnection] > Connecting to provisioning XPC service
[17-04-2024 20:01:10.55] [Debug] [XPCConnection] > Connection result: success()
[17-04-2024 20:01:10.56] [Debug] [XPCConnection] > XPC API version: SemanticVersion(version: "3.36.1")
```

**Comment by dz0ny** [comment]
Hi,

can you test this version which is not Setapp specific build?

https://github.com/ParetoSecurity/pareto-mac/releases/download/1.7.80/ParetoSecurity.dmg

**Comment by zonemaster42** [comment]
I tested the version you sent me. I noticed the following odd behavior:

At first appearance, the “Checks” page was blank.
I then noticed a scroll bar.
I scrolled down & found the checks.
Deselecting any check crashes Pareto Security.
When restarting the app, that check is now turned off.

The behavior is identical on the Setapp version.

Stanley Lubiak
***@***.***

- My Karma ran over your Dogma -

￼

**Comment by zonemaster42** [comment]
Please note that my MacBook Pro was completely erased & macOS was reinstalled on **March 20th, 2024**. Setapp & Pareto Security were also reinstalled shortly after. This version of Pareto Security was **functioning properly** at that time.

Pareto Security did not fail on my MacBook until after I removed it & performed a clean install of version 1.7.81 Build: 5441.
I did this to try to reproduce the error I was having on my 2019 iMac.

You might want to look into whatever changes were made to Pareto Security and/or macOS 14.4 **after March 20th.**

I hope this helps.

**Comment by zonemaster42** [comment]
As a further test, I performed the following actions on my 2019 iMac:

1. Uninstalled both Lulu & BlockBlock apps.
2. Uninstalled Pareto Security via CleanMyMac X.
3. Performed a cleanup via CleanMyMac X.
4. Used the EasyFind app to locate & delete any leftover niteo/pareto files.
5. Rebooted.
6. Reinstalled the 1.7.80 version of Pareto you supplied.
7. The "Checks" option page is still faulty & crashes Pareto when clicked.

**Comment by zupo** [comment]
Thanks for taking the time to posting such a detailed report. We're looking into it!

**Comment by dz0ny** [comment]
Hi,
Can you run the app to the point where it crashes? Then, in the browser bar, paste the following link: https://paretosecurity.com/logs and press Enter. Then, paste the output to this ticket.
Thanks!

This seems do be some sort of Swift UI bug that I cannot reproduce, on m1+ macs. Seems to be related to macOS saving the position of the scrollbar.

**Comment by dz0ny** [comment]
Build 1.7.81 on 14.4.1 virtual macOS works as expected. 
https://github.com/ParetoSecurity/pareto-mac/assets/239513/24163969-a97d-4760-838f-b80e85bd26b7

@zonemaster42 

Can your run [paretosecurity://reset](paretosecurity://reset) via browser (copy+paste then go) adn reprot if you still see the issue?

**Comment by zonemaster42** [comment]
When I tried "https://paretosecurity.com/logs” I got a 404 error.

iMac
Retina 5K, 27-inch, 2019
Processor 3.7 GHz 6-Core Intel Core i5
Graphics Radeon Pro 580X 8 GB
Memory 64 GB 2667 MHz DDR4
Startup disk MacIntosh SSD
macOS Sonoma 14.4.1

**Comment by dmurko** [comment]
Sorry about that, the URL is `paretosecurity://logs`.

**Comment by zonemaster42** [comment]
It still fails after the reset.

**Comment by dz0ny** [comment]
Can you try this release https://github.com/ParetoSecurity/pareto-mac/releases/tag/1.7.83

**Comment by zonemaster42** [comment]
I will try 1.7.83, but first an _interesting development_:

1. I installed 1.7.81 (Setapp) on an M1 Mac mini that I hadn't used for a while. It **FAILED** the same way the Intel Macs had failed.
2. I installed 1.7.80 (which you supplied) on a Parallels VM running macOS 14.4.1 and a **DIFFERENT iCloud account**. It **WORKED PERFECTLY!**

In summary:

1. I have two (2) Intel Macs & one (1) M1 Mac using my primary iCloud account that all fail the same.
2. Running Pareto under a different iCloud account works perfectly!

The problem seems to be propagating via my iCloud account which is shared between my three machines. Do you have any suggestions on how I might break the chain? Is there a specific sequence of uninstalling,  iCloud logout, etc that might fix this situation?

**Comment by dz0ny** [comment]
One case would be custom checks, but you would have to select the iCloud Drive as a source for them.
