### ISSUE TITLE
[Bug]: Multiple instances of the Preferences can be opened at the same time

### ISSUE THREAD

**Issue by pryley** [ParetoSecurity/pareto-mac#144]
### What happened?

Multiple instances of the Preferences window can be opened at the same time on macOS Sequoia 15.0

<img width="667" alt="image" src="https://github.com/user-attachments/assets/18b3e085-fd04-40a6-ad5e-4ed3c021cf43">

### Version

1.7.85 - 5450

**Comment by zupo** [comment]
Thanks for the report, we'll have a look!

**Comment by dz0ny** [comment]
This is now resolved.
