### ISSUE TITLE
[Bug]: No visible feedback if the app is updating/already updated

### ISSUE THREAD

**Issue by suryasr007** [ParetoSecurity/pareto-mac#43]
### What happened?

When I click on update, I have no clue if the app is being updated/already updated.

<img src=https://user-images.githubusercontent.com/10533926/131852515-598be369-600a-4e7a-b9f9-0a34d2e60239.png width="300">

### Expected behavior:
* A check mark beside the `Update` option if the app is already up-to-date.
* A rotating circle beside the `Update` option if the app is being updated.
* A exclamation mark beside the `Update` option if an update is available.

### Version

HW: MacBook Pro13
macOS: Version 11.5.2
App Version: 1.0.0
Build: 1394

**Comment by dmurko** [comment]
I think a success screen would be enough to solve this issue.
