### ISSUE TITLE
[Bug]: Remote Management reporting error

### ISSUE THREAD

**Issue by jimmhay** [ParetoSecurity/pareto-mac#50]
### What happened?

Remote Management test is failing, even though RM is turned off. 

### Version

HW: MacBookAir10,1
macOS: Version 11.5.2 (Build 20G95)
App Version: 1.1.2
Build: 1733

**Comment by zupo** [comment]
@dz0ny: any ideas yet?

**Comment by dmurko** [comment]
Jimmy will let us know the time for a call tomorrow. Janez needs to have a look at what's running on the computer to cause the check to fail.

**Comment by dz0ny** [comment]
Something is running on port 88 that is used for remote management in macOS.
