### ISSUE TITLE
[Bug]: Multiple downloads

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-mac#51]
### What happened?

If I leave the download page opened, I get multiple DMGs downloaded.

<img width="922" alt="Screenshot 2021-09-13 at 20 19 54" src="https://user-images.githubusercontent.com/311580/133150646-801d9d3c-225f-47a5-8535-fda7d705bedd.png">

### Version

Any

**Comment by zupo** [comment]
Probably caused by our auto-refresh JS script in combination with auto-download JS script.

**Comment by dz0ny** [comment]
Fixed
