### ISSUE TITLE
Shortcut to System Preferences

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-mac#52]
### What happened?

Might be useful to people to have `Open System Preferences` button in the menu.

### Version

/

**Comment by zupo** [comment]
Reported by @uzupan.

**Comment by dz0ny** [comment]
They have :) 

![image](https://user-images.githubusercontent.com/239513/133208106-6a630a81-2ed5-47dc-bdc7-c58e66dee758.png)

**Comment by dmurko** [comment]
Also CMD+space and System Preferences.

I think this would be a bit weird. If we could make all shortcuts open the preferences, now that would make sense. But some are not possible (ie Boot secure).

**Comment by zupo** [comment]
Can we do a menu item that when you click it, shows the user to click the apple icon + System Preferences, like so:

<img width="945" alt="Screenshot 2021-09-14 at 14 50 54" src="https://user-images.githubusercontent.com/311580/133270127-bec1c822-4732-4b8c-b0e8-fe0c04d9d9eb.png">

**Comment by zupo** [comment]
@dz0ny: have you done any research yet if this^^ is possible?

**Comment by dz0ny** [comment]
No, that's not possible for menu bar apps. It would have to become dock app.

**Comment by zupo** [comment]
OK, we'll revisit this if we ever become a full-fledged app.
