### ISSUE TITLE
[Idea]: Show tooltip/layover when app is first run so people notice it

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-mac#53]
### What happened?

When you first install the app, "nothing happens". I.e. if you don't see the pareto icon in the menubar, you don't know the app even started. 

### Version

HW: MacBookPro16,2
macOS: Version 11.5.2 (Build 20G95)
App Version: 1.1.3
Build: 1832

**Comment by zupo** [comment]
Reported by @uzupan.

**Comment by dmurko** [comment]
Related: https://github.com/niteoweb/pareto/issues/80

**Comment by dz0ny** [comment]
Done in https://github.com/ParetoSecurity/pareto-mac/releases/tag/1.2.2
