### ISSUE TITLE
[idea]: Warn user that they will have to click "Open" a few times 

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-mac#54]
### What happened?

Before app can be first run the user needs to click "Open"/"Allow" a few times. 

It's good practice to tell the user in advance this will happen so they can expect it.

### Version

HW: MacBookPro16,2
macOS: Version 11.5.2 (Build 20G95)
App Version: 1.1.3
Build: 1832

**Comment by zupo** [comment]
Reported by @uzupan.

**Comment by dmurko** [comment]
Where to add? We say that on the [thanks page](https://paretosecurity.app/thanks/download). It should be just one confirmation though.

**Comment by zupo** [comment]
No, there are two. One for "this app was downloaded from the internet" and the other is something about "this app needs access to system settings".

**Comment by dmurko** [comment]
Hm, I never got that one. We'll need to redocument the process then.

**Comment by zupo** [comment]
Saw it twice today when snooping on people installing the app for the first time.

**Comment by dmurko** [comment]
Added more info to the activate page.

<img width="964" alt="Screenshot 2021-09-20 at 10 53 35" src="https://user-images.githubusercontent.com/1309671/133977541-7b2d91f3-e934-4655-9116-ec6ddfd6345f.png">
