### ISSUE TITLE
[Bug]: App not responding

### ISSUE THREAD

**Issue by am-on** [ParetoSecurity/pareto-mac#72]
### What happened?

Can't open the app. The only thing I see is the loading icon
<img width="1494" alt="Screenshot 2021-11-12 at 15 37 28" src="https://user-images.githubusercontent.com/8530224/141484157-1ef84929-1624-4bae-916e-3ca2e285271c.png">

https://user-images.githubusercontent.com/8530224/141484249-dac57171-03af-46ff-acdb-ad7b7ec67d5e.MOV

### Version

1.4.1

**Comment by am-on** [comment]
The last report sent to Teams was on `2021-11-12T13:08:40.000Z`. Can I get any useful logs?

**Comment by dz0ny** [comment]
Close it, the Sentry will capture the error and send it next to the app starts. Other than that it's not possible to get info out.

**Comment by am-on** [comment]
It keeps happening. It might be related to connecting to VPN. I don't see anything in sentry

**Comment by dz0ny** [comment]
Replicated :) I'ts connectivity check.
