### ISSUE TITLE
[Bug]: Not responding

### ISSUE THREAD

**Issue by jone** [ParetoSecurity/pareto-mac#76]
### What happened?

I have noticed that the pareto app was not responding on my machine. It was no longer visible in the bar at the top.
I had to force-quit and restart it, now it works again.
Other team mates have the same behavior.

Where can I grab logs?

### Version

HW: MacBookPro14,1
macOS: 11.6.0
App Version: 1.4.6
Build: 3068

**Comment by dz0ny** [comment]
Hi,

we have just released the fix for it https://github.com/ParetoSecurity/pareto-mac/releases/tag/1.4.9, it should update automatically if you want to force the update, you can C/P `paretosecurity://update` to the browser.

**Comment by jone** [comment]
Awesome, thank you 🎉
