### ISSUE TITLE
[Bug]: slack updated but reported out-of-date

### ISSUE THREAD

**Issue by KevinHenrikson** [ParetoSecurity/pareto-mac#80]
### What happened?

A bug happened! app reporting slack is out-dated and update available today (Dec 3rd) but slack native install (not app store) says app is latest.

Slack version:
Version 4.22.0
d2ae781b9eab4fbbfcbff805d506653a1205d804@1638475647 (Production)

also https://slack.com/downloads/mac shows 4.22.0 as the latest client

### Version

HW: MacBookAir9,1
macOS: 11.6.1
App Version: 1.6.6
Build: 3471

**Comment by zupo** [comment]
Hey @KevinHenrikson, thanks for the bug report!

I verified it works for me:

<img width="454" alt="Screenshot 2021-12-03 at 22 31 42" src="https://user-images.githubusercontent.com/311580/144681532-d9facd3c-b7fd-4e62-8962-2e87117a2604.png">

I have same app version and build, same macOS version, similar hardware (intel-based macbook pro 13"). 

However, my Slack is installed via App Store. So this might in fact be the culprit. Let's see ...

**Comment by dz0ny** [comment]
Resolved in latest relase.
