### ISSUE TITLE
[Bug]: False positive Remote Login

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-mac#86]
### What happened?

I have Remote Login off but Pareto says it is on.

<img width="690" alt="Screenshot 2021-12-08 at 11 49 23" src="https://user-images.githubusercontent.com/311580/145203791-8144f807-885b-484a-8a64-adc1c1050a87.png">

### Version

1.6.8 - 3541

**Comment by zupo** [comment]
I played around with VirtualBox yesterday, so maybe it's related? It's turned off at the moment though.

**Comment by dz0ny** [comment]
Yep ssh server on port 22

**Comment by zupo** [comment]
Ah yes, I knew it was VirtualBox related. I thought all images will shutdown when I shutdown VirtualBox, alas one was running and listening on 22.
