### ISSUE TITLE
[Bug]: Broken link

### ISSUE THREAD

**Issue by rokcancer** [ParetoSecurity/pareto-mac#89]
### What happened?

System Integrity/FileVault link is broken

It takes me to the following url:
https://paretosecurity.com/check/c3aee29a-f16d-4573-a861-b3ba0d860067?utm_source=app-live-personal

### Version

HW: MacBook Pro (Retina, 15-inch, Mid 2015)
macOS: 11.6.1
App Version: 1.6.16
Build: 3629

**Comment by zupo** [comment]
Hey @rokcancer, when I click your link in a private browsing window, I see this:

<img width="1098" alt="Screenshot 2021-12-13 at 21 24 16" src="https://user-images.githubusercontent.com/311580/145891113-24c1d49f-d6a7-4c1b-941d-372c00188046.png">

Do you see something else? Or do you also see this and you expected to see something else?

**Comment by zupo** [comment]
Ah, I see @dz0ny already beat me to this, and deployed a fix before I realized what's going on :)

So, this should work now, and I'm closing the issue. @rokcancer if it still doesn't work for you, please let me know.
