### ISSUE TITLE
[Bug]: ExpressVPN not recognized for wifi connection

### ISSUE THREAD

**Issue by KevinHenrikson** [ParetoSecurity/pareto-mac#94]
### What happened?

Using wifi with ExpressVPN but check saying not secure.
<img width="843" alt="Screen Shot 2021-12-15 at 1 21 51 PM" src="https://user-images.githubusercontent.com/4099923/146277871-5fa1aad6-9c5f-4dc9-8cab-881ff4c326fb.png">

Logs cut off due to #

### Version

1.6.20 - 3658

### Relevant log output

```shell
State:
Location: /Applications/Pareto Security.app
Build: release
Distribution: direct
ParetoCheck-05423213-50e7-4535-ac88-60cc21626378-Enabled=1
ParetoCheck-05423213-50e7-4535-ac88-60cc21626378-Passes=1
ParetoCheck-05423213-50e7-4535-ac88-60cc21626378-TS=1639607365452
ParetoCheck-0ae675c9-1fbe-5fcc-8e4a-c0f53f4d8b4d-Enabled=1
ParetoCheck-0ae675c9-1fbe-5fcc-8e4a-c0f53f4d8b4d-Passes=0
ParetoCheck-0ae675c9-1fbe-5fcc-8e4a-c0f53f4d8b4d-TS=0
<...snip...>
```

**Comment by zupo** [comment]
Thanks for the report! We tested a couple of different VPNs, but not ExpressVPN specifically. Time to change that!

**Comment by dz0ny** [comment]
This will be fixed in the next release, thanks for the report.
