### ISSUE TITLE
[Bug]: Don't use Google DNS

### ISSUE THREAD

**Issue by zupo** [ParetoSecurity/pareto-mac#99]
### What happened?

A user reported we should not use Google's DNS but something more privacy oriented. 

The culprit is this: https://github.com/ParetoSecurity/pareto-mac/blob/7f950af68f79cdcfa3eb2e2244fb4ebf12bda6fb/Pareto/Flags.swift#L38

### Version

1.6.29

**Comment by zupo** [comment]
Refs https://secure.helpscout.net/conversation/1758747593/33498/

**Comment by dz0ny** [comment]
This has been resolved.
